run 'autoreconf -vif' (see below) so that 'configure' script checks for in6_pktinfo (due to new check in 'configure.ac' from rev 2091)
This should avoid the following compile error:
===
gcc -DHAVE_CONFIG_H -DSYSCONFDIR=\"/usr/local/dragon/etc/\" -I. -I.. -I.. -I.. -I../lib  -g  -g -MT network.o -MD -MP -MF .deps/network.Tpo -c -o network.o network.c
In file included from network.c:23:
./zebra.h:212: error: redefinition of 'struct in6_pktinfo'
make[2]: *** [network.o] Error 1
===

root@max-vlsr:~/snapshot.current/dragon-sw/zebra# autoreconf -vif
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'




git-svn-id: file:///var/www/svn/dragon-sw/trunk@2093 625cd551-afe4-0310-9ad4-9d199310cf85