Fixed an odd problem which seemed to be affecting kip (older Linux box) where passing --with-snmp=/usr to ./configure caused the following compilation error for kom-rsvp:
[We now default to --with-snmp=/usr/local if the net-snmp includes are
found in both /usr and /usr/include...I haven't completely tracked
this one down yet, but something else must be going on because the
/usr/include/net-snmp and /usr/local/include/net-snmp files are all
exactly the same on kip -- i verified and compared the MD5 sums of all
of the header files and they are exactly the same.  configure.in
doesn't seem to be doing anything all that special when passing the
--with-snmp parameter.]

g++   -g -Wall     -include /home/chris/src/dragon-sw/kom-rsvp/RSVP_config.h  -I/usr/include -I/home/chris/src/dragon-sw/kom-rsvp/include  -o /home/chris/src/dragon-sw/kom-rsvp/objects/common/RSVP_BasicTypes.o -c */RSVP_BasicTypes.cc
In file included from /home/chris/src/dragon-sw/kom-rsvp/include/RSVP_GeneralMemoryMachine.h:6,
                 from /home/chris/src/dragon-sw/kom-rsvp/include/RSVP_BasicTypes.h:34,
                 from /home/chris/src/dragon-sw/kom-rsvp/include/RSVP_Lists.h:34,
                 from /home/chris/src/dragon-sw/kom-rsvp/include/RSVP_ProtocolObjects.h:34,
                 from generic/RSVP_API_StateBlock.h:34,
                 from generic/RSVP_API.h:34,
                 from generic/RSVP_API.cc:31:
/home/chris/src/dragon-sw/kom-rsvp/include/RSVP_System.h:68: declaration of `long int strtol (const 
char *, char **, int)' throws different exceptions
/usr/include/stdlib.h:164: than previous declaration `long int strtol 
(const char *, char **, int) throw ()'
In file included from generic/RSVP_GeneralMemoryMachine.h:6,
                 from generic/RSVP_BasicTypes.h:34,
                 from generic/RSVP_IntServComponents.h:34,
                 from generic/RSVP_IntServObjects.h:35,
                 from generic/RSVP_FlowDescriptor.h:34,
                 from generic/RSVP_FlowDescriptor.cc:31:
/home/chris/src/dragon-sw/kom-rsvp/include/RSVP_System.h:68: declaration of `long int strtol (const 
char *, char **, int)' throws different exceptions
/usr/include/stdlib.h:164: than previous declaration `long int strtol 
(const char *, char **, int) throw ()'
In file included from generic/RSVP_GeneralMemoryMachine.h:6,
                 from generic/RSVP_BasicTypes.h:34,
                 from generic/RSVP_BasicTypes.cc:31:
/home/chris/src/dragon-sw/kom-rsvp/include/RSVP_System.h:68: declaration of `long int strtol (const 
char *, char **, int)' throws different exceptions
/usr/include/stdlib.h:164: than previous declaration `long int strtol 
(const char *, char **, int) throw ()'
gmake[1]: *** [RSVP_BasicTypes.o] Error 1
gmake[1]: *** Waiting for unfinished jobs....
gmake[1]: *** [RSVP_FlowDescriptor.o] Error 1
gmake[1]: Leaving directory `/home/chris/src/dragon-sw/kom-rsvp/src/common'
gmake: *** [common] Error 2
gmake: *** Waiting for unfinished jobs....
generic/RSVP_API.cc: In function `void zTearRsvpResvRequest (void *, 
_sessionParameters *)':
generic/RSVP_API.cc:631: warning: unused variable `FLOWSPEC_Object 
*flowspec'
gmake[1]: *** [RSVP_API.o] Error 1
gmake[1]: Leaving directory `/home/chris/src/dragon-sw/kom-rsvp/src/api'
gmake: *** [api] Error 2
dragon-sw: kom-rsvp gmake error!
[root@kip-180 dragon-sw]# 




git-svn-id: file:///var/www/svn/dragon-sw/trunk@1600 625cd551-afe4-0310-9ad4-9d199310cf85